server:
  port: 8009
spring:
  application:
    name: 'cliente-service'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deliveryclienteregister?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456aBc!
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true